# default in local
spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: test_ci